"""add activity leader_user_id

Revision ID: 7e4e41e341cf
Revises: 84d446de94ef
Create Date: 2025-11-14 00:48:25.942964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4e41e341cf'
down_revision = '84d446de94ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_user_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['leader_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('leader_user_id')

    # ### end Alembic commands ###
